# Generated by Django 3.2 on 2021-04-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=35)),
                ('nationality', models.CharField(max_length=40)),
                ('born', models.DateField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=35)),
                ('nationality', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('nationality', models.CharField(max_length=40)),
                ('production_company', models.CharField(max_length=35)),
                ('year_release', models.PositiveIntegerField()),
                ('budget', models.PositiveBigIntegerField()),
                ('box_office', models.PositiveBigIntegerField()),
                ('running_time', models.PositiveSmallIntegerField()),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_role', models.CharField(max_length=35)),
                ('is_main_character', models.BooleanField()),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actor')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
