# Generated by Django 3.2 on 2021-04-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='_name',
            new_name='name_field',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='_name',
            new_name='name_field',
        ),
        migrations.RenameField(
            model_name='movieactor',
            old_name='_role',
            new_name='role_field',
        ),
        migrations.AlterModelTable(
            name='actor',
            table='actor',
        ),
        migrations.AlterModelTable(
            name='director',
            table='director',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='movieactor',
            table='movie_actor',
        ),
    ]
