# Generated by Django 3.2 on 2021-04-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210418_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id_director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movieactor',
            old_name='id_actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movieactor',
            old_name='id_movie',
            new_name='movie',
        ),
    ]
