# Generated by Django 3.2 on 2021-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_release',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
