# Generated by Django 3.2 on 2021-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210522_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='nationality',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_company',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
